name: dog
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - fastai=2.7.9
  - ipykernel=6.16.0
  - ipython=8.5.0
  - ipywidgets=8.0.2
  - jupyter_core=4.11.1
  - jupyterlab_widgets=3.0.3
  - matplotlib=3.6.0
  - numpy=1.23.3
  - pandas=1.5.0
  - pillow=9.2.0
  - pip=22.2.2
  - py-opencv==4.6
  - python=3.9.13
  - pytorch=1.10.2
  - torchvision=0.11.3
  - pip:
    - gradio==3.4
